name: Deploy App Engine to GCloud

on:
  push:
    branches:
      - master
      - java11

jobs:
  deploy:
    name: Deploy using GCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare environment secrets
        run: |
          printf "${{ secrets.SECRET_TXT }}" > backend/src/main/resources/secret.txt
          printf "${{ secrets.GCP_SA_KEY }}" > backend/src/main/resources/mixtio-191009221320.json

      - name: Assembly
        run: sbt backend/assembly
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to GCloud
        run: |
          gcloud app deploy --quiet --project mixtio backend/target/scala-2.12/mixtio.jar --appyaml=backend/web/WEB-INF/app.yaml
          gcloud app deploy --quiet --project mixtio backend/web/WEB-INF/cron.yaml
